# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: split_schema.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'split_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12split_schema.proto\x12\rsplitlearning\"I\n\x06Tensor\x12\x0f\n\x07is_null\x18\x01 \x01(\x08\x12\x10\n\x08raw_data\x18\x02 \x01(\x0c\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\r\n\x05\x64type\x18\x04 \x01(\t\"\x9e\x02\n\rClientRequest\x12\x13\n\x0b\x63lient_name\x18\x01 \x01(\t\x12,\n\rlayers_output\x18\x02 \x03(\x0b\x32\x15.splitlearning.Tensor\x12\x10\n\x08img_name\x18\x03 \x01(\t\x12\x11\n\timg_shape\x18\x04 \x03(\x03\x12\x12\n\norig_shape\x18\x05 \x03(\x03\x12\x16\n\x0elast_layer_idx\x18\x06 \x01(\x05\x12\x11\n\ttimestamp\x18\x07 \x01(\x01\x12\x16\n\x0einference_time\x18\x08 \x01(\x01\x12\x1e\n\x16message_send_timestamp\x18\t \x01(\x01\x12\x15\n\rclient_ram_mb\x18\n \x01(\x01\x12\x17\n\x0f\x63lient_cpu_perc\x18\x0b \x01(\x01\"/\n\x0bServerReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2f\n\x15SplitInferenceService\x12M\n\x0fSendActivations\x12\x1c.splitlearning.ClientRequest\x1a\x1a.splitlearning.ServerReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'split_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSOR']._serialized_start=37
  _globals['_TENSOR']._serialized_end=110
  _globals['_CLIENTREQUEST']._serialized_start=113
  _globals['_CLIENTREQUEST']._serialized_end=399
  _globals['_SERVERREPLY']._serialized_start=401
  _globals['_SERVERREPLY']._serialized_end=448
  _globals['_SPLITINFERENCESERVICE']._serialized_start=450
  _globals['_SPLITINFERENCESERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
