# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import split_schema_pb2 as split__schema__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in split_schema_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SplitInferenceServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendActivations = channel.unary_unary(
                '/splitlearning.SplitInferenceService/SendActivations',
                request_serializer=split__schema__pb2.ClientRequest.SerializeToString,
                response_deserializer=split__schema__pb2.ServerReply.FromString,
                _registered_method=True)


class SplitInferenceServiceServicer(object):
    """The service definition.
    """

    def SendActivations(self, request, context):
        """Sends client activations to the server
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SplitInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendActivations': grpc.unary_unary_rpc_method_handler(
                    servicer.SendActivations,
                    request_deserializer=split__schema__pb2.ClientRequest.FromString,
                    response_serializer=split__schema__pb2.ServerReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'splitlearning.SplitInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('splitlearning.SplitInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SplitInferenceService(object):
    """The service definition.
    """

    @staticmethod
    def SendActivations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/splitlearning.SplitInferenceService/SendActivations',
            split__schema__pb2.ClientRequest.SerializeToString,
            split__schema__pb2.ServerReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
